version: "3.9"
services:
  sirpef_laravel_carnets:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sirpef_laravel_carnets
    env_file:
      - .env
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - store-network
  sirpef_laravel_nginx_carnets:
    depends_on:
      - sirpef_laravel_carnets
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: sirpef_laravel_nginx_carnets
    restart: unless-stopped
    tty: true
    volumes:
      - "./public:/var/www/html/public:ro"
      - "./storage/app:/var/www/html/storage/app:ro"
    ports:
      - "8002:80"
    networks:
      - store-network      

networks:
  store-network:
    driver: bridge


