version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:81"
    environment:
      NODE_ENV: production
    container_name: sirpef_carico_dev
